services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: flask --app api run --debug --host=0.0.0.0
    ports:
      - '5000:5000'
    volumes:
      - .:/app

  web:
    build:
      context: web
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0
    environment:
      API_PROXY_TARGET: http://api:5000
    ports:
      - '5173:5173'
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.svelte-kit
